### ISSUE TITLE
can this be updated to windows 11?

### ISSUE THREAD

**Issue by Yusuf007R** [adrian88888888/AHK_Virtual_Desktop_Library#5]
I know you are not the creator of the dll (I have already put a issue there), but do you think is there any other way around?

**Comment by itzjakm** [comment]
Check this repo: https://github.com/skottmckay/VirtualDesktopAccessor

**Comment by Yusuf007R** [comment]
thanks dude, works perfect.

**Comment by adrian88888888** [comment]
Thanks itzjakm!
